export const routes = {
  home: "/",
  about: "/o-vermilion",
  aboutENG: "/about-vermilion",
  publications: "/publikacje",
  publicationsENG: "/publications",
  weddingCollection: "/kolekcja-ślubna",
  weddingCollectionENG: "/wedding-collection",
  eveningCollection: "/kolekcja-wieczorowa",
  eveningCollectionENG: "/evening-collection",
  underbustCollection: "/kolekcja-underbust",
  underbustCollectionENG: "/underbust-collection",
  overbustCollection: "/kolekcja-overbust",
  overbustCollectionENG: "/overbust-collection",
  couture: "/couture",
  contact: "/kontakt",
  contactENG: "/contact",
  singleProduct: "/product/:productName",
  askedQuestions: "/pytania-i-odpowiedzi",
  askedQuestionsENG: "/frequently-asked-questions",
  fabrics: "/tkaniny",
  fabricsENG: "/fabrics",
};
